'use strict';
const $=id=>document.getElementById(id), num=id=>Number($(id).value), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let plans=[],runs=[],editId=null,selectedId=null,view='connections',live=[],lastSample=null,lastRecording=false,reviewRows=[],pairedRows=[],derived={},reviewMeta={},aggregateRows=[],profileLoaded=false,lastHardware=null;
const colors=['#007ea7','#d25b14','#c9262c','#008b75'];
let subsetDirty=false;
let batchState={state:'idle',items:[]},currentPhase='idle',rippleResults={rows:[],excluded:[]};
async function get(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
async function send(action,values={}){const r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...values})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d}
function bind(id,fn){$(id).addEventListener('click',async()=>{const b=$(id);b.disabled=true;$('error').textContent='';try{await fn()}catch(e){$('error').textContent=e.message}finally{b.disabled=false}})}
function say(text){$('message').textContent=text}
function show(name){const aliases={home:'connections',troubleshoot:'connections',frequency:'review',compare:'review',scripts:'connections'};name=aliases[name]||name;if(!$('view-'+name))name='connections';view=name;document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===name)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});history.replaceState(null,'','#'+name);document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+name);if(name==='live'||name==='connections')readiness().catch(showError);if(name==='review'){refreshRuns().catch(showError);loadResults().catch(showError);refreshFrequencyRuns().catch(showError)}if(name==='tuning')refreshTuning().catch(showError);window.scrollTo(0,0);drawAll()}
function showError(e){$('error').textContent=e.message}
// The menu uses native anchor links, including keyboard navigation and deep links.
window.addEventListener('hashchange',()=>show(location.hash.slice(1)));
function planForm(){return {method:$('plan-method').value,test_type:$('plan-type').value,rpm:num('plan-rpm'),load_a:num('plan-load'),repeat:num('plan-repeat'),duration_s:num('plan-duration'),settle_rpm:num('plan-tolerance'),settle_load_a:num('plan-load-tolerance'),settle_s:num('plan-hold'),notes:$('plan-notes').value,capture_high_rate:$('plan-capture').checked}}
function fillPlan(p){editId=p.id;$('plan-capture').checked=p.capture_high_rate===true;$('edit-title').textContent='Edit planned run';for(const [id,key]of [['plan-method','method'],['plan-type','test_type'],['plan-rpm','rpm'],['plan-load','load_a'],['plan-repeat','repeat'],['plan-duration','duration_s'],['plan-tolerance','settle_rpm'],['plan-load-tolerance','settle_load_a'],['plan-hold','settle_s'],['plan-notes','notes']])$(id).value=p[key]}
function renderPlans(){const filter=$('plan-filter').value;const counts={};plans.forEach(p=>counts[p.status]=(counts[p.status]||0)+1);$('plan-counts').textContent=plans.length+' planned · '+Object.entries(counts).map(([k,n])=>n+' '+k).join(' · ');$('plan-table').innerHTML=plans.filter(p=>filter==='all'||p.status===filter).map(p=>`<tr class="${p.id===selectedId?'selected-row':''}"><td><input type="checkbox" data-plan="${esc(p.id)}" aria-label="Include ${esc(p.id)}" ${p.selected?'checked':''}></td><td title="${esc(p.id)}">${esc(p.id.slice(-8))}</td><td>${esc(p.method)}</td><td>${p.rpm.toFixed(1)}</td><td>${p.load_a.toFixed(2)}</td><td>${esc(p.test_type)}</td><td>${p.repeat}</td><td><span class="pill">${esc(p.status)}</span><br>${esc(p.reason)}</td><td><button data-use="${esc(p.id)}">Select</button><button data-edit="${esc(p.id)}">Edit</button></td></tr>`).join('')}
async function refreshPlans(){const incoming=await get('/api/plans');if(subsetDirty)for(const p of incoming){const old=plans.find(o=>o.id===p.id);if(old)p.selected=old.selected}plans=incoming;renderPlans();renderMatrix()}
$('plan-filter').addEventListener('change',renderPlans);
$('plan-table').addEventListener('change',e=>{if(e.target.dataset.plan){const p=plans.find(p=>p.id===e.target.dataset.plan);p.selected=e.target.checked;subsetDirty=true;renderMatrix()}});
$('plan-table').addEventListener('click',async e=>{try{if(e.target.dataset.edit){fillPlan(plans.find(p=>p.id===e.target.dataset.edit));window.scrollTo(0,0)}if(e.target.dataset.use){const p=await send('select',{id:e.target.dataset.use});selectedId=p.id;$('mode').value=p.method;$('rpm').value=p.rpm;$('load').value=p.load_a;renderPlans();renderMatrix();showSelected();say('Point selected. Run selected test starts this point when board checks pass.')}}catch(err){showError(err)}});
bind('new-plan',()=>{editId=null;$('edit-title').textContent='Add a test';say('Next save adds a new plan.')});
bind('save-plan',async()=>{await send('plan',{...planForm(),...(editId?{id:editId}:{})});await refreshPlans();say('Test saved. Select it to check readiness.')});
bind('generate',async()=>{const result=await send('matrix',{...planForm(),test_type:'steady state',speed_base:num('speed-base'),load_base:num('load-base'),speeds:$('speed-fractions').value.split(',').map(Number),loads:$('load-fractions').value.split(',').map(Number)});await refreshPlans();say(`${result.created} paired plans added. Exclude infeasible points before running.`)});
bind('select-visible',()=>{const f=$('plan-filter').value;plans.forEach(p=>{if(f==='all'||p.status===f)p.selected=true});subsetDirty=true;renderPlans();renderMatrix()});
bind('clear-subset',()=>{plans.forEach(p=>p.selected=false);subsetDirty=true;renderPlans();renderMatrix()});
bind('save-subset',async()=>{await send('subset',{ids:plans.filter(p=>p.selected).map(p=>p.id)});subsetDirty=false;say('Subset saved.')});
bind('skip-selected',async()=>{await send('skip',{ids:plans.filter(p=>p.selected).map(p=>p.id),reason:$('skip-reason').value});await refreshPlans();say('Skipped plans retained with their reasons.')});
function showChecks(checks){return checks.map(c=>`<div class="quality-item"><strong>${esc(c.name)}</strong> <span class="${esc(c.state)}">${esc(c.state)}</span><br><small>${esc(c.detail)}</small></div>`).join('')}
async function readiness(){const r=await get('/api/readiness');$('readiness').innerHTML=showChecks(r.checks);$('connection-readiness').innerHTML=showChecks(r.hardware.readiness);$('hardware-report').textContent=JSON.stringify(r.hardware,null,2);renderTroubleshooting(r.hardware);return r}
bind('check-ready',readiness);
bind('apply',async()=>{await send('start',{rpm:num('rpm'),load_a:num('load'),mode:$('mode').value});say('Start / apply command accepted. Watch both board states and live measurements.')});
for(const id of ['stop','global-stop'])bind(id,async()=>{await send('stop');await refreshPlans();say('Coast stop requested on both boards. Check their reported states.')});
bind('run-test',async()=>{if(!selectedId)throw Error('Select a pending point from the test matrix first.');await send('run_test',{id:selectedId});show('plan');say('Selected-point workflow started: settle, record, then coast stop.')});
bind('record',async()=>{await send('record',{allow_unsettled:$('unsettled').checked});await refreshPlans();say('Recording started. It continues independently of this browser.')});
bind('finish',async()=>{await send('end_record');await refreshPlans();await refreshRuns();say('Recording finished; review the acquisition before accepting it.')});

const profileFields={'test-serial':'test_serial','load-serial':'load_serial','max-speed':'max_speed_rpm','max-load':'max_load_a','test-direction':'test_direction','load-direction':'load_direction','poll-rate':'polling_hz','stop-policy':'stop_policy','roles-verified':'roles_verified','units-verified':'axis_units_verified','stop-verified':'stop_policy_verified','sensorless-verified':'sensorless_startup_verified','sensorless-min':'sensorless_min_rpm','encoder-path':'encoder_reference_path','encoder-scale':'encoder_reference_scale_rad','encoder-speed-path':'encoder_speed_path','encoder-speed-scale':'encoder_speed_scale_rpm','encoder-verified':'encoder_reference_verified','capture-bandwidth':'capture_bandwidth_hz','capture-filtering':'capture_filtering'};
const numericProfile=new Set(['max-speed','max-load','test-direction','load-direction','poll-rate','sensorless-min','encoder-scale','encoder-speed-scale','capture-bandwidth']);
function fillProfile(p){for(const [id,key] of Object.entries(profileFields)){const el=$(id);if(el.type==='checkbox')el.checked=p[key]===true;else el.value=p[key]??''}profileLoaded=true}
function readProfile(){const p={};for(const [id,key] of Object.entries(profileFields)){const el=$(id);p[key]=el.type==='checkbox'?el.checked:numericProfile.has(id)?(el.value.trim()===''?null:Number(el.value)):el.value.trim()}return p}
bind('save-connection',async()=>{const h=await send('configure_connection',{profile:readProfile()});fillProfile(h.profile);say('Connection profile saved. No board configuration was written.');await readiness()});
bind('connect',async()=>{await send('connect');live=[];lastSample=null;await readiness();say('Boards connected for read-only monitoring. Motion requires Start or Run selected test.')});
bind('disconnect',async()=>{await send('disconnect');live=[];lastSample=null;drawLive();await readiness();say('Board connections released.')});
bind('clear-errors',async()=>{await send('clear_errors');await readiness();say('Error-clear command sent. Check reported board errors before starting.')});
const liveSpecs=[{id:'position',title:'Rotor position · turns',keys:['position_revolutions'],labels:['Position'],span:1},
{id:'speed',title:'Rotor speed · rpm',keys:['speed_rpm'],labels:['Speed'],span:100},
{id:'phase',title:'Three-phase currents · A',keys:['ia_a','ib_a','ic_a'],labels:['Phase A','Phase B','Phase C'],span:.2}];
const reviewSpecs=[{id:'angle',title:'Electrical-angle error · deg',keys:['angle_error_deg'],labels:['Estimated − independent reference'],span:1},
{id:'phase',title:'Phase currents · A',keys:['ia_a','ib_a','ic_a'],labels:['Ia','Ib','Ic'],span:.2},
{id:'dq',title:'Id / Iq · A',keys:['drive_id_a','drive_iq_a','id_reference_a','iq_reference_a'],labels:['Controller Id','Controller Iq','Encoder-reference Id','Encoder-reference Iq'],span:.2},
{id:'rpm',title:'Speed · rpm',keys:['encoder_rpm','command_rpm','estimated_rpm'],labels:['Independent encoder','Command','Estimator'],span:100},
{id:'bus',title:'DC bus voltage · V',keys:['drive_dc_voltage_v','load_dc_voltage_v'],labels:['Test','Load'],span:1},
{id:'branch',title:'Branch DC current · A',keys:['drive_dc_current_a','load_dc_current_a'],labels:['Test','Load'],span:.2}];
function chartCards(container,specs,prefix){$(container).innerHTML=specs.map(s=>`<article class="panel"><h2>${s.title}</h2><div class="legend">${s.labels.map((l,i)=>`<span style="color:${colors[i]}">${l} <b id="${prefix}-${s.id}-${i}" class="metric-value"></b></span>`).join('')}</div><canvas id="${prefix}-${s.id}" aria-label="${s.title}"></canvas></article>`).join('')}
for(const role of ['test','load'])chartCards(role+'-live-charts',liveSpecs,role);
chartCards('review-charts',reviewSpecs,'review');
function chart(id,series,minSpan,range,windowRange,xUnit='s'){const c=$(id);if(!c||c.clientWidth<1)return;const g=c.getContext('2d'),w=c.clientWidth,h=Math.max(140,Math.round(c.clientHeight||240)),dpr=window.devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;g.setTransform(dpr,0,0,dpr,0,0);const left=62,right=w-(xUnit==='rpm'?40:12),top=16,bottom=h-32;let values=[];for(const s of series)for(const p of s.points)if(Number.isFinite(p.y))values.push(p.y);if(!values.length){g.fillStyle='#526973';g.font='14px system-ui';g.fillText('Channel unavailable in this dataset',15,100);return}let low=values.reduce((a,b)=>Math.min(a,b),Infinity),high=values.reduce((a,b)=>Math.max(a,b),-Infinity),span=Math.max(minSpan,high-low),mid=(high+low)/2;low=mid-span*.6;high=mid+span*.6;let lo=range[0],hi=range[1];if(hi<=lo)hi=lo+1;const x=t=>left+(t-lo)/(hi-lo)*(right-left),y=v=>bottom-(v-low)/(high-low)*(bottom-top);g.font='11px system-ui';g.textAlign='right';g.fillStyle='#526973';for(let i=0;i<=4;i++){let v=low+(high-low)*i/4,py=y(v);g.strokeStyle='#d9e6e4';g.beginPath();g.moveTo(left,py);g.lineTo(right,py);g.stroke();g.fillText(Math.abs(v)>=100?v.toFixed(0):v.toFixed(2),left-8,py+4)}g.textAlign='center';for(let i=0;i<=3;i++){const t=lo+(hi-lo)*i/3;g.fillText((xUnit==='rpm'?t.toFixed(0):t.toFixed(2))+' '+xUnit,x(t),bottom+22)}g.save();g.beginPath();g.rect(left,top,right-left,bottom-top);g.clip();if(windowRange){g.fillStyle='#ffeb7f55';g.fillRect(x(windowRange[0]),top,x(windowRange[1])-x(windowRange[0]),bottom-top);g.strokeStyle='#007ea7';for(const t of windowRange){g.beginPath();g.moveTo(x(t),top);g.lineTo(x(t),bottom);g.stroke()}}
for(const s of series){g.strokeStyle=s.color;g.lineWidth=1.6;g.setLineDash(s.dash||[]);g.beginPath();let last=null;const dt=s.points.length>1?(s.points[s.points.length-1].t-s.points[0].t)/(s.points.length-1):1;for(const p of s.points){if(!Number.isFinite(p.y)){last=null;continue}if(last!==null&&p.t-last<Math.max(dt*2.5,.0001))g.lineTo(x(p.t),y(p.y));else g.moveTo(x(p.t),y(p.y));last=p.t}g.stroke();if(s.markers){g.setLineDash([]);g.fillStyle=s.color;for(const p of s.points)if(Number.isFinite(p.y)){g.beginPath();g.arc(x(p.t),y(p.y),3.5,0,Math.PI*2);g.fill()}}}g.restore()}
function drawLive(){const end=live.length?live[live.length-1].time_s:0;for(const role of ['test','load'])for(const spec of liveSpecs){const board=lastHardware?.boards[role];const series=spec.keys.map((key,i)=>{const available=board?.connected&&Number.isFinite(board.signals[key]);const label=$(role+'-'+spec.id+'-'+i);label.style.color=colors[i];label.textContent=available?board.signals[key].toFixed(2):'unavailable';return {color:colors[i],points:available?live.map(r=>({t:r.time_s-end,y:r[role]?.[key]})):[]}});chart(role+'-'+spec.id,series,spec.span,[-30,0])}}
function drawReview(){if(!reviewRows.length)return;const t=reviewRows.map(r=>r.time_s);for(const spec of reviewSpecs){const series=spec.keys.map((key,i)=>({color:colors[i],points:derived[key]?derived.time_s.map((x,j)=>({t:x,y:derived[key][j]})):reviewRows.map(r=>({t:r.time_s,y:r[key]}))}));if(pairedRows.length){const offset=reviewRows[0].time_s-pairedRows[0].time_s;spec.keys.forEach((key,i)=>series.push({color:colors[i],dash:[5,5],points:pairedRows.map(r=>({t:r.time_s+offset,y:r[key]}))}))}chart('review-'+spec.id,series,spec.span,[t.reduce((a,b)=>Math.min(a,b),Infinity),t.reduce((a,b)=>Math.max(a,b),-Infinity)],[num('window-start'),num('window-end')])}}
function drawAll(){if(view==='live')drawLive();if(view==='review'){drawReview();drawRipple();drawSpectra()}if(view==='tuning')drawTuning()}
window.addEventListener('resize',drawAll);for(const id of ['window-start','window-end'])$(id).addEventListener('input',drawReview);

async function refreshRuns(){runs=await get('/api/runs');const old=$('review-run').value;$('review-run').innerHTML=runs.map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(-8))} · ${esc(r.plan.method)} · ${r.plan.rpm} rpm / ${r.plan.load_a} A · repeat ${r.plan.repeat} · ${esc(r.status)}</option>`).join('');if(runs.some(r=>r.id===old))$('review-run').value=old;await chooseRun()}
async function chooseRun(){const id=$('review-run').value;if(!id){$('run-summary').textContent='No recorded runs yet.';return}const run=await get('/api/run?id='+encodeURIComponent(id));$('run-summary').textContent=`${run.plan.method} · ${run.plan.rpm} rpm · ${run.plan.load_a} A · repeat ${run.plan.repeat} · ${run.status} · ${run.datasets.length} dataset${run.datasets.length===1?'':'s'}`;const old=$('review-dataset').value;$('review-dataset').innerHTML='<option value="telemetry">Continuous telemetry</option>'+run.datasets.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');$('review-dataset').value=run.datasets.includes(old)?old:(run.datasets[0]||'telemetry');$('run-metadata').textContent=JSON.stringify(run,null,2);$('download').href='/download?id='+encodeURIComponent(id);$('paired-run').innerHTML='<option value="">None</option>'+runs.filter(r=>r.id!==id&&r.plan.rpm===run.plan.rpm&&r.plan.load_a===run.plan.load_a&&r.plan.repeat===run.plan.repeat&&r.plan.method!==run.plan.method&&r.plan.test_type===run.plan.test_type&&r.status!=='recording').map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(-8))} · ${esc(r.plan.method)} · ${esc(r.source)}</option>`).join('');$('window-type').value=run.plan.test_type==='steady state'?'steady state':'transient';if(run.latest_review)renderResult(run.latest_review.summary);else{$('quality').textContent='No analysis yet.';$('metrics').innerHTML=''}reviewRows=[];pairedRows=[];derived={};for(const s of reviewSpecs){const c=$('review-'+s.id);c.getContext('2d').clearRect(0,0,c.width,c.height)}}
$('review-run').addEventListener('change',()=>chooseRun().catch(showError));bind('refresh-runs',refreshRuns);
async function loadData(){const data=await get('/api/data?id='+encodeURIComponent($('review-run').value)+'&dataset='+encodeURIComponent($('review-dataset').value));reviewRows=data.rows;reviewMeta=data.metadata;pairedRows=[];derived={};if(!reviewRows.length)throw Error('Dataset is empty.');$('window-start').value=reviewRows[0].time_s;$('window-end').value=reviewRows[reviewRows.length-1].time_s;$('dataset-info').textContent=`${data.original_samples} raw samples · display every ${data.display_stride} sample(s) · ${data.metadata.source} · ${data.metadata.acquisition.source}. Time is this dataset's original clock.`;$('overlay-info').textContent='Overlay clocks are not assumed synchronized.';drawReview()}
bind('load-data',loadData);
function settings(){return {start_s:num('window-start'),end_s:num('window-end'),window_type:$('window-type').value,max_timing_angle_deg:num('timing-budget'),...($('fundamental').value?{fundamental_hz:num('fundamental')}:{})}}
function renderResult(result){$('quality').innerHTML=`<p class="${result.valid_acquisition?'pass':'error'}">${result.valid_acquisition?'Acquisition checks passed for this window':'Acquisition checks failed or insufficient data'}</p>`+(result.quality_flags||[]).map(f=>`<div class="quality-item ${esc(f.severity)}">${esc(f.message)}</div>`).join('');const timing=result.timing||{};$('metrics').innerHTML=`<tr><th>Actual mean sample rate</th><td>${timing.actual_mean_hz?.toFixed(2)??'unavailable'} Hz</td></tr><tr><th>Timing gaps</th><td>${timing.gap_count??'unavailable'}</td></tr>`+Object.entries(result.metrics||{}).map(([key,val])=>`<tr><th>${esc(key)}</th><td>${esc(typeof val==='object'?JSON.stringify(val):val)}</td></tr>`).join('')}
bind('analyze',async()=>{const result=await send('review',{run_id:$('review-run').value,dataset:$('review-dataset').value,settings:settings()});renderResult(result);derived=result.derived||{};drawReview();say('Analysis saved as a new revision; raw data unchanged.')});
bind('overlay',async()=>{const id=$('paired-run').value;if(!id){pairedRows=[];drawReview();return}if(!reviewRows.length)throw Error('Load the primary dataset first.');const other=await get('/api/run?id='+encodeURIComponent(id));const dataset=$('review-dataset').value==='telemetry'?'telemetry':other.datasets.find(d=>d.startsWith('capture_'));if(!dataset)throw Error('Paired run has no matching capture type.');const data=await get('/api/data?id='+encodeURIComponent(id)+'&dataset='+encodeURIComponent(dataset));pairedRows=data.rows;$('overlay-info').textContent='Dashed: paired run, aligned by each dataset start for comparison only. This is not clock synchronization. Primary shaded window and metrics apply only to the primary run.';drawReview()});
bind('retry',async()=>{const p=await send('repeat',{run_id:$('review-run').value});await refreshPlans();selectedId=p.id;$('mode').value=p.method;$('rpm').value=p.rpm;$('load').value=p.load_a;say('New attempt planned with the same repeat number. Earlier attempts remain intact.');show('live')});
bind('save-note',async()=>{await send('note',{run_id:$('review-run').value,note:$('review-note').value});say('Note appended to the event log.')});
bind('accept',async()=>{await send('accept',{run_id:$('review-run').value,outcome:$('outcome').value,reason:$('review-note').value});await refreshPlans();await refreshRuns();say('Review saved. Next selected pending plan is ready for manual application.')});
$('mapping').value=JSON.stringify({time_s:{column:'Time',unit:'s',scale:1,offset:0,kind:'measured'},ia_a:{column:'Ia',unit:'A',scale:1,offset:0,kind:'measured'},ib_a:{column:'Ib',unit:'A',scale:1,offset:0,kind:'measured'},ic_a:{column:'Ic',unit:'A',scale:1,offset:0,kind:'measured'}},null,2);
$('import-meta').value=JSON.stringify({instrument:'',calibration_id:'',acquisition:{requested_hz:null,bandwidth_hz:null,filtering:'',anti_alias_verified:false,switching_hz:null,ranges:{},synchronization:{method:'',simultaneous:false,uncertainty_s:null}},calibration:{verified:false,id:'',pole_pairs:null,offset_rad:null,encoder_direction:1},independent_encoder_provenance:'',device_serials:{test:null,load:null},firmware:null},null,2);
bind('import',async()=>{const file=$('import-file').files[0];if(!file)throw Error('Choose a CSV file.');if(file.size>8000000)throw Error('CSV must be smaller than 8 MB.');const result=await send('import',{run_id:$('review-run').value,source:$('import-source').value,csv:await file.text(),mapping:JSON.parse($('mapping').value),metadata:JSON.parse($('import-meta').value)});await chooseRun();$('review-dataset').value=result.dataset;await loadData();say('Original CSV, normalized channels and provenance saved.')});
async function aggregate(){aggregateRows=await get('/api/aggregate?metric='+encodeURIComponent($('aggregate-metric').value));$('aggregate-table').innerHTML=aggregateRows.map((r,i)=>`<tr><td>${esc(r.source)}</td><td>${esc(r.method)}</td><td>${r.rpm}</td><td>${r.load_a}</td><td>${r.n}</td><td>${r.mean.toPrecision(5)}</td><td>${r.std===null?'Requires another repeat':r.std.toPrecision(4)}</td><td>${i+1}</td></tr>`).join('')||'<tr><td colspan="8">No compatible completed analyses for this metric.</td></tr>';const groups={};for(const r of aggregateRows){const key=JSON.stringify([r.source,r.method,r.test_type,r.group_signature]);(groups[key]??=[]).push(r)}let html='';for(const rows of Object.values(groups)){const speeds=[...new Set(rows.map(r=>r.rpm))].sort((a,b)=>a-b),loads=[...new Set(rows.map(r=>r.load_a))].sort((a,b)=>a-b);if(speeds.length<2||loads.length<2||rows.filter(r=>r.n>=2).length<4){html+=`<p>${esc(rows[0].source+' · '+rows[0].method)}: insufficient coverage for a map (need four cells with ≥2 independent repeats spanning two speeds and two loads).</p>`;continue}const max=Math.max(...rows.map(r=>r.mean),.000001);html+=`<div class="map table-wrap"><h3>${esc(rows[0].source+' · '+rows[0].method)}</h3><table><thead><tr><th>rpm / A</th>${loads.map(l=>`<th>${l} A</th>`).join('')}</tr></thead><tbody>${speeds.map(s=>`<tr><th>${s} rpm</th>${loads.map(l=>{const r=rows.find(r=>r.rpm===s&&r.load_a===l);return r&&r.n>=2?`<td style="background:rgba(0,201,167,${.1+.6*r.mean/max})">${r.mean.toPrecision(4)}<br><small>n=${r.n}</small></td>`:'<td>Insufficient data</td>'}).join('')}</tr>`).join('')}</tbody></table></div>`}$('maps').innerHTML=html||'<p>Maps appear after sufficient valid repeat coverage.</p>'}
bind('aggregate',aggregate);
function matrixState(p){if(p.id===selectedId&&['settling','capturing','recording','processing'].includes(currentPhase))return currentPhase;const item=batchState.items?.find(i=>i.id===p.id);if(item)return item.state==='running'?currentPhase:item.state;return p.status==='awaiting review'?'recorded':p.status}
function renderMatrix(){
 const speeds=[...new Set(plans.map(p=>p.rpm))].sort((a,b)=>a-b),loads=[...new Set(plans.map(p=>p.load_a))].sort((a,b)=>a-b);
 const html=plans.length?`<table class="matrix-table"><thead><tr><th>Load / speed</th>${speeds.map(s=>`<th>${s} rpm</th>`).join('')}</tr></thead><tbody>${loads.map(l=>`<tr><th>${l} A</th>${speeds.map(s=>`<td><div class="matrix-cell">${plans.filter(p=>p.rpm===s&&p.load_a===l).map(p=>{const state=matrixState(p);return `<button class="matrix-point ${esc(state)} ${p.id===selectedId?'chosen':''} ${p.selected?'':'excluded'}" data-point="${esc(p.id)}" aria-pressed="${p.id===selectedId}" title="${esc(p.method+' · '+p.test_type+' · repeat '+p.repeat+' · '+state)}"><strong>${p.method==='sensored'?'Sensored':'Sensorless'}</strong><span>Repeat ${p.repeat} · ${esc(state)}</span></button>`}).join('')}</div></td>`).join('')}</tr>`).join('')}</tbody></table>`:'<div class="empty-state">No tests planned yet. Open “Configure tests” below to add a point or generate the paired matrix.</div>';
 if($('visual-matrix').innerHTML!==html)$('visual-matrix').innerHTML=html;
 const items=batchState.items||[],done=items.filter(i=>i.state==='recorded').length;
 $('batch-progress').textContent=items.length?`${done} / ${items.length} recorded · ${batchState.state}${batchState.reason?' · '+batchState.reason:''}`:'Choose a test tile, or run all included pending tests.';
 $('batch-meter').max=items.length||1;$('batch-meter').value=done;
 const reserved=['running','paused'].includes(batchState.state);
 $('run-test').disabled=reserved||!plans.some(p=>p.id===selectedId&&p.status==='pending');
 $('run-all').disabled=reserved||!plans.some(p=>p.selected&&p.status==='pending');
 $('resume-batch').hidden=batchState.state!=='paused';$('cancel-batch').hidden=!reserved;showSelected();
}
$('visual-matrix').addEventListener('click',async e=>{const b=e.target.closest('[data-point]');if(!b)return;try{const p=await send('select',{id:b.dataset.point});selectedId=p.id;$('mode').value=p.method;$('rpm').value=p.rpm;$('load').value=p.load_a;renderMatrix();renderPlans();say('Test selected. Click Run selected to begin.')}catch(err){showError(err)}});
bind('run-all',async()=>{const ids=plans.filter(p=>p.selected&&p.status==='pending').map(p=>p.id);if(!ids.length)throw Error('Include at least one pending test.');batchState=await send('batch_start',{ids});renderMatrix();say('Batch started. It will pause if a point cannot run or a test fails.')});
bind('resume-batch',async()=>{batchState=await send('batch_resume');renderMatrix()});
bind('cancel-batch',async()=>{await send('batch_cancel');await refreshPlans();say('Batch cancelled and coast stop requested.')});
bind('zero-position',async()=>{await send('zero_position');live=[];lastSample=null;drawLive();say('Both displayed positions now start at zero. Raw board positions are retained in recordings.')});

async function loadResults(){rippleResults=await get('/api/results');renderRipple()}
function renderRipple(){
 const rows=rippleResults.rows||[];
 $('results-progress').textContent=`${rows.length} valid repeat results · ${(rippleResults.excluded||[]).length} excluded runs. ${rippleResults.note||''}`;
 $('results-exclusions').innerHTML=(rippleResults.excluded||[]).map(r=>`<p><strong>${esc(r.run_id.slice(-8))}</strong> · ${esc(r.reason)}</p>`).join('')||'<p>No excluded runs.</p>';
 $('results-table').innerHTML=rows.map(r=>`<tr><td>${esc(r.run_id.slice(-8))}</td><td>${esc(r.method)}</td><td>${r.rpm}</td><td>${r.load_a}</td><td>${r.repeat}</td><td>${r.peak_to_peak.toPrecision(5)}</td><td>${r.abs_peak.toPrecision(5)}</td><td>${r.accepted?'Accepted':'Awaiting acceptance'}</td></tr>`).join('');
 const groups=rippleGroups();
 $('ripple-charts').innerHTML=groups.length?groups.map((rows,i)=>`<article class="panel"><p class="eyebrow">LOAD ${rows[0].load_a} A</p><h2>Current ripple vs speed</h2><p class="small">${esc(rows[0].comparison.source||'Capture')} · ${esc(rows[0].comparison.requested_hz??'?')} samples/s · bandwidth ${esc(rows[0].comparison.bandwidth_hz??'?')} Hz · acquisition group ${i+1}</p><div class="legend"><span style="color:${colors[0]}">● Sensored</span><span style="color:${colors[1]}">● Sensorless</span></div><p class="small" id="ripple-y-${i}"></p><canvas id="ripple-${i}" aria-label="Maximum current ripple in amperes against speed in rpm at load ${rows[0].load_a} amperes"></canvas><p class="small">${rows.length} valid repeats. Each point shows the largest value across repeats. Missing results remain gaps.</p></article>`).join(''):'<div class="empty-state">No valid phase-current results yet. Record steady-state captures, then click Process results. The exclusion list explains any missing points.</div>';
 drawRipple();
}
function rippleGroups(){const groups=new Map();for(const r of rippleResults.rows||[]){const key=JSON.stringify([r.load_a,r.comparison_key]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}return [...groups.values()].sort((a,b)=>a[0].load_a-b[0].load_a)}
function drawRipple(){
 const metric=$('ripple-metric').value;
 $('results-definition').textContent=(metric==='peak_to_peak'?'Maximum peak-to-peak residual':'Maximum absolute residual')+' · A. DC and the fitted fundamental are removed separately from phases A, B and C. The largest phase value is used; each plotted point is the maximum across valid repeats within the same acquisition group.';
 rippleGroups().forEach((rows,i)=>{
  const speeds=[...new Set([...rows.map(r=>r.rpm),...plans.filter(p=>p.load_a===rows[0].load_a&&p.test_type==='steady state').map(p=>p.rpm)])].sort((a,b)=>a-b);
  const series=['sensored','sensorless'].map((method,j)=>({color:colors[j],markers:true,points:speeds.map(rpm=>{const vals=rows.filter(r=>r.method===method&&r.rpm===rpm).map(r=>r[metric]);return {t:rpm,y:vals.length?Math.max(...vals):null}})}));
  $('ripple-y-'+i).textContent=(metric==='peak_to_peak'?'Maximum peak-to-peak residual':'Maximum absolute residual')+' · A';
  const lo=Math.min(...rows.map(r=>r.rpm)),hi=Math.max(...rows.map(r=>r.rpm)),pad=Math.max(1,(hi-lo)*.04);chart('ripple-'+i,series,.001,[lo-pad,hi+pad],null,'rpm');
 });
}
bind('process-results',async()=>{say('Processing original capture samples…');rippleResults=await send('process_results',{settings:{}});renderRipple();say('Results processed and saved. Both ripple measurements are available for export.')});
$('ripple-metric').addEventListener('change',drawRipple);
let settingsToken=null,troubleshootLoaded=false;
function invalidateSettings(){settingsToken=null;$('settings-preview').hidden=true}
function renderTroubleshooting(h,force=false){
 const p=h.profile,cfg=r=>h.boards[r].configuration||{},value=(v,u='')=>v===null||v===undefined?'unavailable':String(v)+u;
 const topics=[['Local rig limits','Set positive validated speed and load limits below. Zero deliberately disables motor commands.',`Speed: ${value(p.max_speed_rpm,' rpm')} · Load: ${value(p.max_load_a,' A')}`]];
 for(const role of ['test','load']){const c=cfg(role),title=role==='test'?'Test':'Load';topics.push([title+' watchdog','Enable the watchdog with a timeout compatible with the polling rate.',`Enabled: ${value(c['axis0.config.enable_watchdog'])} · Timeout: ${value(c['axis0.config.watchdog_timeout'],' s')}`]);topics.push([title+' controller mode',role==='test'?'Required: velocity control (2), velocity ramp (2), positive validated speed ramp.':'Required: torque control (1), torque ramp (6), positive validated torque ramp.',`Control mode: ${value(c['axis0.controller.config.control_mode'])} · Input mode: ${value(c['axis0.controller.config.input_mode'])}`])}
 $('troubleshoot-checks').innerHTML=topics.map(([name,help,current])=>{const check=h.readiness.find(c=>c.name===name);return `<article class="panel"><span class="pill ${esc(check?.state||'waiting')}">${esc(check?.state||'Connect to inspect')}</span><h3>${esc(name)}</h3><p>${esc(current)}</p><p>${esc(help)}</p></article>`}).join('');
 $('existing-limits').textContent=`Test board velocity limit: ${value(!Number.isFinite(cfg('test')['axis0.controller.config.vel_limit'])?null:cfg('test')['axis0.controller.config.vel_limit']*60,' rpm')} · Load board current limit: ${value(cfg('load')['axis0.config.motor.current_soft_max'],' A')}.`;
 const minimum=Math.max(.5,6/p.polling_hz);$('watchdog-range').textContent=`At ${p.polling_hz} Hz polling, the accepted timeout is ${minimum.toFixed(2)}–2.00 s.${minimum>2?' Increase polling to at least 3 Hz in Connections.':''}`;
 if(force||!troubleshootLoaded){$('fix-speed').value=p.max_speed_rpm||'';$('fix-load').value=p.max_load_a||'';for(const role of ['test','load']){const c=cfg(role);const timeout=c['axis0.config.watchdog_timeout'];$('fix-'+role+'-watchdog').value=Number.isFinite(timeout)&&timeout>=minimum&&timeout<=2?timeout:Math.max(1,minimum);$('fix-'+role+'-ramp').value=role==='test'?(c['axis0.controller.config.vel_ramp_rate']===undefined?'':c['axis0.controller.config.vel_ramp_rate']*60):(c['axis0.controller.config.torque_ramp_rate']??'')}troubleshootLoaded=true;}
 if(h.settings_result){$('settings-outcome').textContent=h.settings_result.state+(h.settings_result.error?' · '+h.settings_result.error:'');$('settings-report').textContent=JSON.stringify(h.settings_result,null,2)}
}
for(const id of ['fix-test-watchdog','fix-load-watchdog','fix-test-ramp','fix-load-ramp'])$(id).addEventListener('input',invalidateSettings);
bind('refresh-settings',async()=>{invalidateSettings();const h=await send('refresh_settings');renderTroubleshooting(h,true);await readiness();say('Current settings read from the connected boards.')});
bind('fix-limits',async()=>{const h=await send('update_limits',{max_speed_rpm:num('fix-speed'),max_load_a:num('fix-load')});fillProfile(h.profile);invalidateSettings();await readiness();say('Local rig limits saved. Board current and voltage limits were not changed.')});
bind('preview-settings',async()=>{invalidateSettings();const h=await send('preview_settings',{values:{test_watchdog_s:num('fix-test-watchdog'),load_watchdog_s:num('fix-load-watchdog'),test_ramp_rpm_s:num('fix-test-ramp'),load_ramp_nm_s:num('fix-load-ramp')}});settingsToken=h.settings_preview.token;$('settings-changes').innerHTML=h.settings_preview.changes.map(c=>`<tr><td>${esc(c.role)}<br>${esc(c.serial)}</td><td>${esc(c.path)}</td><td>${esc(c.before)}</td><td>${esc(c.after)}</td></tr>`).join('');$('settings-preview').hidden=false;$('persist-settings').checked=false;say('Preview ready. Review the board identities and proposed values before Apply.')});
bind('apply-settings',async()=>{if(!settingsToken)throw Error('Preview the changes first.');const token=settingsToken;invalidateSettings();try{const h=await send('apply_settings',{token,persist:$('persist-settings').checked});renderTroubleshooting(h,true);say('Settings update finished. Check the verified changes and remaining blockers.')}finally{await readiness()}});
let frequencyData={};
async function refreshFrequencyRuns(){
 const items=await get('/api/runs'),old=$('frequency-run').value;
 $('frequency-run').innerHTML=items.filter(r=>r.datasets?.some(d=>d.startsWith('capture_'))).map(r=>`<option value="${esc(r.id)}">${esc(r.id.slice(-8))} · ${esc(r.plan.method)} · ${r.plan.rpm} rpm / ${r.plan.load_a} A</option>`).join('');
 if(items.some(r=>r.id===old))$('frequency-run').value=old;
 await loadSpectra();
}
async function loadSpectra(){
 const id=$('frequency-run').value;
 frequencyData=id?await get('/api/spectra?id='+encodeURIComponent(id)):{};
 $('frequency-note').textContent=Object.keys(frequencyData).length?'The shaded band surrounds the requested electrical frequency. Compare its integrated A² with the rest of the measured range.':'No saved spectra for this run. Recalculate from its original high-rate captures if available.';
 for(const role of ['test','load']){
  const s=frequencyData[role],el=$('frequency-'+role+'-summary');
  el.innerHTML=s?`<p>${s.target_fraction===null?'No current variance to compare.':`<strong>${(100*s.target_fraction).toFixed(1)}%</strong> of resolved phase-current variance in the desired band; <strong>${(100*(1-s.target_fraction)).toFixed(1)}%</strong> elsewhere.`}</p><p>Desired ${s.desired_electrical_hz.toFixed(1)} Hz · band ${s.desired_band_hz.map(x=>x.toFixed(1)).join('–')} Hz · ${s.target_to_outside_db===null?'ratio unavailable':s.target_to_outside_db.toFixed(1)+' dB target/outside'}</p><p class="small">${esc(s.samples)} samples at ${s.sample_rate_hz.toFixed(0)} Hz; ${s.resolution_hz.toFixed(1)} Hz bins. ${esc(s.meaning)}</p>`:'<p>No valid onboard phase-current spectrum available.</p>';
 }
 drawSpectra();
}
function drawSpectra(){
 for(const role of ['test','load']){
  const canvas=$('frequency-'+role+'-chart'),s=frequencyData[role];if(!canvas||canvas.clientWidth<1)continue;
  const w=canvas.clientWidth,h=270,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const g=canvas.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);
  if(!s){g.fillStyle='#526973';g.fillText('Spectrum unavailable',20,60);continue}
  const max=$('frequency-range').value==='full'?s.nyquist_hz:Math.min(500,s.nyquist_hz),left=62,right=w-16,top=15,bottom=h-34;
  const pairs=s.frequency_hz.map((f,i)=>[f,s.mean_psd_a2_per_hz[i]]).filter(([f,p])=>f>0&&f<=max&&p>0);
  if(!pairs.length)continue;
  const minLog=Math.floor(Math.log10(Math.min(...pairs.map(x=>x[1])))),maxLog=Math.ceil(Math.log10(Math.max(...pairs.map(x=>x[1]))));
  const px=f=>left+f/max*(right-left),py=p=>bottom-(Math.log10(p)-minLog)/Math.max(1,maxLog-minLog)*(bottom-top);
  g.fillStyle='#ffeb7f88';g.fillRect(px(s.desired_band_hz[0]),top,Math.max(1,px(Math.min(max,s.desired_band_hz[1]))-px(s.desired_band_hz[0])),bottom-top);
  g.strokeStyle='#d9e6e4';g.fillStyle='#526973';g.font='11px system-ui';
  for(let i=0;i<=4;i++){const f=max*i/4,x=px(f);g.beginPath();g.moveTo(x,top);g.lineTo(x,bottom);g.stroke();g.fillText(f.toFixed(0)+' Hz',Math.max(left,Math.min(right-32,x-14)),h-12)}
  for(let e=minLog;e<=maxLog;e++){const y=py(10**e);g.beginPath();g.moveTo(left,y);g.lineTo(right,y);g.stroke();g.fillText('1e'+e,7,y+3)}
  g.strokeStyle='#007ea7';g.lineWidth=1.7;g.beginPath();pairs.forEach(([f,p],i)=>i?g.lineTo(px(f),py(p)):g.moveTo(px(f),py(p)));g.stroke();
  g.strokeStyle='#d5262a';g.setLineDash([4,4]);g.beginPath();g.moveTo(px(s.desired_electrical_hz),top);g.lineTo(px(s.desired_electrical_hz),bottom);g.stroke();g.setLineDash([]);
 }
}
bind('frequency-refresh',loadSpectra);
bind('frequency-reprocess',async()=>{const id=$('frequency-run').value;if(!id)throw Error('Select a captured run.');let completed=0,errors=[];for(const role of ['test','load']){try{await send('spectrum',{run_id:id,dataset:'capture_'+role});completed++}catch(e){errors.push(role+': '+e.message)}}await loadSpectra();if(errors.length)$('frequency-note').textContent+=' '+errors.join(' ');say(completed?`Recalculated ${completed} spectrum${completed===1?'':'s'} from original captures.`:'No spectrum could be calculated; see the reasons above.')});
$('frequency-run').addEventListener('change',()=>loadSpectra().catch(showError));
$('frequency-range').addEventListener('change',drawSpectra);
$('frequency-run').closest('details').addEventListener('toggle',e=>{if(e.target.open)drawSpectra()});
$('aggregate').closest('details').addEventListener('toggle',e=>{if(e.target.open)aggregate().catch(showError)});
let tuningData={state:'idle',trials:[]};
async function refreshTuning(){
 tuningData=await get('/api/tuning');
 $('tuning-state').textContent=`${tuningData.state} · ${tuningData.task||''}`;
 $('tuning-tasks').innerHTML=tuningData.state==='awaiting_operator'?`<div class="quality-item"><strong>Before motion</strong><p>${esc(tuningData.task)}</p><p>1. Verify both ODrive serial numbers and motor roles on Connections.<br>2. Keep people and loose items away from the coupled shafts.<br>3. Confirm the physical stop and USB isolators.<br>4. Stay at the rig while the site runs up to three short trials.</p></div>`:'';
 const g=tuningData.baseline_gains||{},p=tuningData.proposed_gains||{},fmt=v=>Number.isFinite(v)?v.toPrecision(5):'unavailable';
 $('tuning-settings').innerHTML=tuningData.id?`<p>Session ${esc(tuningData.id)} · ${esc(tuningData.role)} · ${tuningData.rpm} rpm · ${tuningData.load_a} A</p><table><thead><tr><th>Gain</th><th>Starting</th><th>Recommended</th></tr></thead><tbody><tr><td>Velocity P</td><td>${fmt(g['axis0.controller.config.vel_gain'])}</td><td>${fmt(p['axis0.controller.config.vel_gain'])}</td></tr><tr><td>Velocity I</td><td>${fmt(g['axis0.controller.config.vel_integrator_gain'])}</td><td>${fmt(p['axis0.controller.config.vel_integrator_gain'])}</td></tr></tbody></table>`:'<p>No session prepared.</p>';
 $('tuning-advice').textContent=tuningData.note||'Complete the readiness checks to begin.';
 $('tuning-metrics').innerHTML=(tuningData.trials||[]).map((t,i)=>`<p><strong>Trial ${i+1} · ${t.factor}× gains</strong> · speed RMS error ${t.metrics.speed_rms_error_rpm.toFixed(2)} rpm · overshoot ${t.metrics.overshoot_rpm.toFixed(2)} rpm · speed variation ${t.metrics.speed_sd_rpm.toFixed(2)} rpm · load Iq RMS error ${t.metrics.load_iq_rms_error_a.toFixed(2)} A</p>`).join('');
 $('tuning-start').disabled=tuningData.state!=='awaiting_operator';$('tuning-cancel').disabled=!['awaiting_operator','running','stopping','restoring'].includes(tuningData.state);
 $('tuning-apply').disabled=tuningData.state!=='review'||tuningData.role!=='test';
 $('tuning-restore').disabled=tuningData.state!=='applied';$('tuning-save').disabled=tuningData.state!=='applied';
 drawTuning();
}
function drawTuning(){
 const last=tuningData.trials?.at(-1),samples=last?.samples||[];
 if(!samples.length){chart('tuning-speed-chart',[],10,[0,1]);return}
 const t0=samples[0].time_s,t1=samples.at(-1).time_s-t0;
 chart('tuning-speed-chart',[{color:colors[0],points:samples.map(s=>({t:s.time_s-t0,y:Math.abs(s.drive_rpm)}))},
  {color:colors[1],dash:[5,5],points:[{t:0,y:tuningData.rpm},{t:t1,y:tuningData.rpm}]}],10,[0,t1]);
}
bind('tuning-check',async()=>{tuningData=await send('tuning_prepare',{role:$('tuning-role').value,rpm:num('tuning-rpm'),load_a:num('tuning-load')});$('tuning-physical').checked=false;await refreshTuning();say('Starting settings saved. Complete the physical task before starting.')});
bind('tuning-start',async()=>{tuningData=await send('tuning_start',{physical_checked:$('tuning-physical').checked});await refreshTuning();say('Guided tuning trials started. Stay at the rig.')});
bind('tuning-cancel',async()=>{tuningData=await send('tuning_cancel');await refreshTuning();say('Tuning stop requested. Wait for both shafts to stop.')});
bind('tuning-apply',async()=>{tuningData=await send('tuning_apply');await refreshTuning();say('Recommended gains applied temporarily. Run a validation test before saving.')});
bind('tuning-restore',async()=>{tuningData=await send('tuning_restore');await refreshTuning();say('Starting gains restored.')});
bind('tuning-save',async()=>{tuningData=await send('tuning_save');await refreshTuning();say('Applied gains saved to the test board. Reconnect and verify persistence.')});
let polls=0;
function showSelected(){const p=plans.find(p=>p.id===selectedId);const text=p?`${p.method} · ${p.rpm} rpm · ${p.load_a} A · ${p.test_type} · repeat ${p.repeat} · ${p.duration_s} s · ${p.status}`:'Select a pending test point in the test matrix.';$('selected-plan').textContent=text;$('matrix-selected').textContent=text;$('matrix-point-card').textContent=p?text+' · settling hold '+p.settle_s+' s · high-rate capture '+(p.capture_high_rate?'required':'optional'):'Select a test tile to see its speed, load, feedback and recording plan.'}
function boardReport(role,b,fresh){const state=b.connected?(fresh?b.state:'STALE DATA'):'DISCONNECTED';const description=`${state} · ${b.serial||'no board'} · ${b.feedback_method||b.feedback||'feedback unavailable'}`;$(role+'-monitor-state').textContent=description;$(role+'-board-state').innerHTML=`<p class="${b.connected&&fresh?'pass':'waiting'}">${esc(description)}</p><p>Firmware: ${esc(b.firmware||'unavailable')}<br>Active errors: ${esc((typeof b.errors==='object'?b.errors?.active_errors:b.errors)??'unavailable')}<br>Disarm reason: ${esc(b.errors?.disarm_reason??b.disarm_reason??'unavailable')}</p><small>High-rate capture: ${esc(b.capture?.available?b.capture.sample_rate_hz+' samples/s · '+b.capture.samples+' samples per buffer':b.capture?.detail||'Connect to check compatibility')}.<br>${Object.values(b.signals).filter(Number.isFinite).length} readable signals. Board read time: ${Number.isFinite(b.read_end_s)&&Number.isFinite(b.read_start_s)?((b.read_end_s-b.read_start_s)*1000).toFixed(1)+' ms':'unavailable'}.</small>`}
async function poll(){try{const d=await get('/api/status');const h=d.hardware;lastHardware=h;selectedId=d.selected;batchState=d.batch||{state:'idle',items:[]};currentPhase=d.run_phase;renderMatrix();if(!profileLoaded)fillProfile(h.profile);
const fresh=Number.isFinite(d.telemetry_age_s)&&d.telemetry_age_s<1;
$('live-state').textContent=`${d.state} · ${d.recording?'RECORDING':d.run_phase==='settling'?'SETTLING':'not recording'} · real boards`;
$('matrix-progress-card').textContent=batchState.items?.length?`${batchState.items.filter(i=>i.state==='recorded').length} of ${batchState.items.length} recorded · ${batchState.state}${batchState.reason?' · '+batchState.reason:''}`:'No sequence running.';
$('package-status').textContent=h.package_installed?`ODrive Python package ${h.package_version} installed.`:'ODrive Python package unavailable. Follow the local setup guide.';
for(const role of ['test','load']){const b=h.boards[role];boardReport(role,b,fresh);const badge=$(role+'-status');badge.textContent=(role==='test'?'Test':'Load')+' ODrive: '+(b.connected?(fresh?b.state:'Stale data'):'Disconnected');badge.classList.toggle('connected',b.connected&&fresh);if(!fresh)b.signals={}}
$('settling').textContent=d.settled?'Settled at selected conditions':'Waiting for selected conditions to settle';$('settling').className=d.settled?'pass':'waiting';
$('record-state').textContent=`${d.recording?'RECORDING':'Not recording'} · target ${d.requested_hz} Hz · observed ${fresh&&Number.isFinite(d.actual_hz)?d.actual_hz.toFixed(1)+' Hz':'unavailable'} · queue ${d.queue_depth} · ${d.run_phase}`;
$('file').textContent=d.file;showSelected();if(d.error)$('error').textContent=d.error;
if(fresh&&h.sample_id!==lastSample){lastSample=h.sample_id;live.push({time_s:h.acquired_at_s,test:{...h.boards.test.signals},load:{...h.boards.load.signals}});live=live.filter(r=>h.acquired_at_s-r.time_s<=30)}
if(!fresh||!Object.values(h.boards).some(b=>b.connected))live=[];if(view==='live')drawLive();
if(lastRecording&&!d.recording){await refreshPlans();if(view==='review')await refreshRuns();say('Recording ended. Raw data is saved for quality review.')}lastRecording=d.recording;
if(++polls%10===0){if(view==='live'||view==='connections'||view==='troubleshoot')await readiness();if(view==='plan')await refreshPlans();if(view==='tuning')await refreshTuning()}
}catch(e){lastHardware=null;live=[];drawLive();$('live-state').textContent='Dashboard connection lost';for(const role of ['test','load']){$(role+'-monitor-state').textContent='Dashboard connection lost · readings unavailable';$(role+'-status').textContent=(role==='test'?'Test':'Load')+' ODrive: Unavailable';$(role+'-status').classList.remove('connected')}$('error').textContent='Dashboard disconnected. The Python controller may still be running; inspect the local application.'}setTimeout(poll,200)}
show(location.hash.slice(1)||'connections');
Promise.all([refreshPlans(),refreshRuns()]).catch(showError).finally(poll);
